version: '3.8'

# Declare all the services that make up Cheli app
services:
    # Define the MySQL database as a service
    cheli_mysql:
        container_name: cheli_mysql
        image: mysql:8.0.32
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # root user is automatically created, we just provide the password
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - database-network
        healthcheck:
            test: [ "CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD" ]
            interval: 5s
            timeout: 20s
            retries: 30

    # Define the Cheli Express API as a service
    cheli_api:
        container_name: cheli_api
        build:
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        restart: always
        environment:
            TREBLLE_API_KEY: ${TREBLLE_API_KEY}
            TREBLLE_PROJECT_ID: ${TREBLLE_PROJECT_ID}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_HOST: ${MYSQL_HOST}
        networks:
            - database-network
        depends_on:
            cheli_mysql:
                condition: service_healthy

# Network is needed so that the API can communicate with the database
networks:
    database-network:
