version: '3.8'

services:
  cheli_postgres:
    container_name: cheli_postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - database-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${PG_USER} -d ${PG_DB_NAME}'"]
      interval: 5s
      timeout: 20s
      retries: 30
    volumes:
      - db:/var/lib/postgresql/data


networks:
  database-network:
volumes:
  db:
    driver: local
